// src/app/layout.tsx
"use client";

import { Nunito, Nunito_Sans } from "next/font/google";
import "./globals.css";
import { useEffect } from "react";
import { ProductPageCache } from "@/components/ProductPageCache";
import { ServiceWorkerUnregister } from "@/components/ServiceWorkerUnregister";

// Nunito untuk headings
const nunito = Nunito({
  variable: "--font-nunito",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800"],
  display: "swap",
});

// Nunito Sans untuk body text (opsional, bisa pakai Nunito juga)
const nunitoSans = Nunito_Sans({
  variable: "--font-nunito-sans", 
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  display: "swap",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  useEffect(() => {
    if (typeof window !== 'undefined' && 'serviceWorker' in navigator && window.workbox !== undefined) {
      const wb = window.workbox;
      // A common UX pattern for progressive web apps is to show a banner when a service worker has updated and waiting to install.
      // NOTE: MUST set skipWaiting: false in next.config.js for this to work.
      wb.addEventListener('waiting', () => {
        // `event.wasWaitingBeforeRegister` will be false if this is the first time the updated service worker is waiting.
        // If true, it means the user ignored the previous logic and there's no need to bug them again.
        if (confirm('A new version is available, would you like to update?')) {
          wb.messageSkipWaiting();
        }
      });

      // `workbox.register()` does all the heavy lifting for you.
      // It will pull in the service worker file generated by the build process and register it for you.
      wb.register();
    }
  }, []);

  return (
    <html lang="id">
      <head>
        <title>HJKARPET - Katalog</title>
        <meta name="description" content="Supplier karpet berkualitas tinggi untuk masjid, kantor, hotel, dan kebutuhan interior lainnya." />
        <meta name="keywords" content="karpet, karpet masjid, karpet kantor, karpet hotel, interior, sajadah" />
        <meta name="author" content="HJKARPET" />
        
        {/* PWA Meta Tags */}
        <link rel="manifest" href="/manifest.json" />
        <meta name="theme-color" content="#ffffff" />
        <meta name="apple-mobile-web-app-capable" content="yes" />
        <meta name="apple-mobile-web-app-status-bar-style" content="default" />
        <meta name="apple-mobile-web-app-title" content="HJKARPET - Katalog" />
        <link rel="apple-touch-icon" href="/icons/icon-192x192.png" />
        
        {/* Open Graph */}
        <meta property="og:title" content="HJKARPET - Katalog" />
        <meta property="og:description" content="Supplier karpet berkualitas tinggi untuk masjid, kantor, hotel, dan kebutuhan interior lainnya." />
        <meta property="og:type" content="website" />
        <meta property="og:locale" content="id_ID" />
        
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body
        className={`${nunito.variable} ${nunitoSans.variable} font-sans antialiased`}
      >
        <ServiceWorkerUnregister />
        <ProductPageCache />
        {children}
      </body>
    </html>
  );
}